// Code generated by go-swagger; DO NOT EDIT.

// Package restapi RelayAccess
//
//  API for accessing github.com/practable/relay websocket relay. Note scheme http and host localhost due to running behind proxy
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.4
//  Contact: Timothy Drysdale<timothy.d.drysdale@gmail.com> https://github.com/timdrysdale
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
