// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupIDByNameParams creates a new GetGroupIDByNameParams object
// with the default values initialized.
func NewGetGroupIDByNameParams() *GetGroupIDByNameParams {
	var ()
	return &GetGroupIDByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupIDByNameParamsWithTimeout creates a new GetGroupIDByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGroupIDByNameParamsWithTimeout(timeout time.Duration) *GetGroupIDByNameParams {
	var ()
	return &GetGroupIDByNameParams{

		timeout: timeout,
	}
}

// NewGetGroupIDByNameParamsWithContext creates a new GetGroupIDByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGroupIDByNameParamsWithContext(ctx context.Context) *GetGroupIDByNameParams {
	var ()
	return &GetGroupIDByNameParams{

		Context: ctx,
	}
}

// NewGetGroupIDByNameParamsWithHTTPClient creates a new GetGroupIDByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGroupIDByNameParamsWithHTTPClient(client *http.Client) *GetGroupIDByNameParams {
	var ()
	return &GetGroupIDByNameParams{
		HTTPClient: client,
	}
}

/*GetGroupIDByNameParams contains all the parameters to send to the API endpoint
for the get group ID by name operation typically these are written to a http.Request
*/
type GetGroupIDByNameParams struct {

	/*Name
	  Search by group name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get group ID by name params
func (o *GetGroupIDByNameParams) WithTimeout(timeout time.Duration) *GetGroupIDByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group ID by name params
func (o *GetGroupIDByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group ID by name params
func (o *GetGroupIDByNameParams) WithContext(ctx context.Context) *GetGroupIDByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group ID by name params
func (o *GetGroupIDByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group ID by name params
func (o *GetGroupIDByNameParams) WithHTTPClient(client *http.Client) *GetGroupIDByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group ID by name params
func (o *GetGroupIDByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get group ID by name params
func (o *GetGroupIDByNameParams) WithName(name string) *GetGroupIDByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get group ID by name params
func (o *GetGroupIDByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupIDByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
