// Code generated by go-swagger; DO NOT EDIT.

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPoolStatusByIDHandlerFunc turns a function with the right signature into a get pool status by ID handler
type GetPoolStatusByIDHandlerFunc func(GetPoolStatusByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPoolStatusByIDHandlerFunc) Handle(params GetPoolStatusByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetPoolStatusByIDHandler interface for that can handle valid get pool status by ID params
type GetPoolStatusByIDHandler interface {
	Handle(GetPoolStatusByIDParams, interface{}) middleware.Responder
}

// NewGetPoolStatusByID creates a new http.Handler for the get pool status by ID operation
func NewGetPoolStatusByID(ctx *middleware.Context, handler GetPoolStatusByIDHandler) *GetPoolStatusByID {
	return &GetPoolStatusByID{Context: ctx, Handler: handler}
}

/*GetPoolStatusByID swagger:route GET /pools/{pool_id}/status pools getPoolStatusById

Gets the status of the pool's activities

Gets the status of pool's activities

*/
type GetPoolStatusByID struct {
	Context *middleware.Context
	Handler GetPoolStatusByIDHandler
}

func (o *GetPoolStatusByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPoolStatusByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
