// Code generated by go-swagger; DO NOT EDIT.

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/timdrysdale/relay/pkg/booking/models"
)

// GetPoolDescriptionByIDOKCode is the HTTP code returned for type GetPoolDescriptionByIDOK
const GetPoolDescriptionByIDOKCode int = 200

/*GetPoolDescriptionByIDOK get pool description by Id o k

swagger:response getPoolDescriptionByIdOK
*/
type GetPoolDescriptionByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ID `json:"body,omitempty"`
}

// NewGetPoolDescriptionByIDOK creates GetPoolDescriptionByIDOK with default headers values
func NewGetPoolDescriptionByIDOK() *GetPoolDescriptionByIDOK {

	return &GetPoolDescriptionByIDOK{}
}

// WithPayload adds the payload to the get pool description by Id o k response
func (o *GetPoolDescriptionByIDOK) WithPayload(payload *models.ID) *GetPoolDescriptionByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pool description by Id o k response
func (o *GetPoolDescriptionByIDOK) SetPayload(payload *models.ID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPoolDescriptionByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
