// Code generated by go-swagger; DO NOT EDIT.

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/timdrysdale/relay/pkg/booking/models"
)

// GetPoolStatusByIDOKCode is the HTTP code returned for type GetPoolStatusByIDOK
const GetPoolStatusByIDOKCode int = 200

/*GetPoolStatusByIDOK get pool status by Id o k

swagger:response getPoolStatusByIdOK
*/
type GetPoolStatusByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Status `json:"body,omitempty"`
}

// NewGetPoolStatusByIDOK creates GetPoolStatusByIDOK with default headers values
func NewGetPoolStatusByIDOK() *GetPoolStatusByIDOK {

	return &GetPoolStatusByIDOK{}
}

// WithPayload adds the payload to the get pool status by Id o k response
func (o *GetPoolStatusByIDOK) WithPayload(payload *models.Status) *GetPoolStatusByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pool status by Id o k response
func (o *GetPoolStatusByIDOK) SetPayload(payload *models.Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPoolStatusByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
