// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/timdrysdale/relay/pkg/booking/models"
)

// NewAddNewGroupParams creates a new AddNewGroupParams object
// no default values defined in spec.
func NewAddNewGroupParams() AddNewGroupParams {

	return AddNewGroupParams{}
}

// AddNewGroupParams contains all the bound params for the add new group operation
// typically these are obtained from a http.Request
//
// swagger:parameters addNewGroup
type AddNewGroupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Group *models.Group
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddNewGroupParams() beforehand.
func (o *AddNewGroupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Group
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("group", "body", ""))
			} else {
				res = append(res, errors.NewParseError("group", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Group = &body
			}
		}
	} else {
		res = append(res, errors.Required("group", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
