// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGroupDescriptionByIDHandlerFunc turns a function with the right signature into a get group description by ID handler
type GetGroupDescriptionByIDHandlerFunc func(GetGroupDescriptionByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGroupDescriptionByIDHandlerFunc) Handle(params GetGroupDescriptionByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGroupDescriptionByIDHandler interface for that can handle valid get group description by ID params
type GetGroupDescriptionByIDHandler interface {
	Handle(GetGroupDescriptionByIDParams, interface{}) middleware.Responder
}

// NewGetGroupDescriptionByID creates a new http.Handler for the get group description by ID operation
func NewGetGroupDescriptionByID(ctx *middleware.Context, handler GetGroupDescriptionByIDHandler) *GetGroupDescriptionByID {
	return &GetGroupDescriptionByID{Context: ctx, Handler: handler}
}

/*GetGroupDescriptionByID swagger:route GET /groups/{group_id} groups getGroupDescriptionById

groups

Gets a description of a group

*/
type GetGroupDescriptionByID struct {
	Context *middleware.Context
	Handler GetGroupDescriptionByIDHandler
}

func (o *GetGroupDescriptionByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGroupDescriptionByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
