// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplacePoolsByGroupIDHandlerFunc turns a function with the right signature into a replace pools by group ID handler
type ReplacePoolsByGroupIDHandlerFunc func(ReplacePoolsByGroupIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplacePoolsByGroupIDHandlerFunc) Handle(params ReplacePoolsByGroupIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReplacePoolsByGroupIDHandler interface for that can handle valid replace pools by group ID params
type ReplacePoolsByGroupIDHandler interface {
	Handle(ReplacePoolsByGroupIDParams, interface{}) middleware.Responder
}

// NewReplacePoolsByGroupID creates a new http.Handler for the replace pools by group ID operation
func NewReplacePoolsByGroupID(ctx *middleware.Context, handler ReplacePoolsByGroupIDHandler) *ReplacePoolsByGroupID {
	return &ReplacePoolsByGroupID{Context: ctx, Handler: handler}
}

/* ReplacePoolsByGroupID swagger:route PUT /groups/{group_id}/pools groups replacePoolsByGroupId

groups

Update list of pool_ids in the group (replace existing). Return new complete list.

*/
type ReplacePoolsByGroupID struct {
	Context *middleware.Context
	Handler ReplacePoolsByGroupIDHandler
}

func (o *ReplacePoolsByGroupID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplacePoolsByGroupIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
