// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportPoolStoreParams creates a new ExportPoolStoreParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportPoolStoreParams() *ExportPoolStoreParams {
	return &ExportPoolStoreParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportPoolStoreParamsWithTimeout creates a new ExportPoolStoreParams object
// with the ability to set a timeout on a request.
func NewExportPoolStoreParamsWithTimeout(timeout time.Duration) *ExportPoolStoreParams {
	return &ExportPoolStoreParams{
		timeout: timeout,
	}
}

// NewExportPoolStoreParamsWithContext creates a new ExportPoolStoreParams object
// with the ability to set a context for a request.
func NewExportPoolStoreParamsWithContext(ctx context.Context) *ExportPoolStoreParams {
	return &ExportPoolStoreParams{
		Context: ctx,
	}
}

// NewExportPoolStoreParamsWithHTTPClient creates a new ExportPoolStoreParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportPoolStoreParamsWithHTTPClient(client *http.Client) *ExportPoolStoreParams {
	return &ExportPoolStoreParams{
		HTTPClient: client,
	}
}

/* ExportPoolStoreParams contains all the parameters to send to the API endpoint
   for the export pool store operation.

   Typically these are written to a http.Request.
*/
type ExportPoolStoreParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export pool store params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportPoolStoreParams) WithDefaults() *ExportPoolStoreParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export pool store params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportPoolStoreParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export pool store params
func (o *ExportPoolStoreParams) WithTimeout(timeout time.Duration) *ExportPoolStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export pool store params
func (o *ExportPoolStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export pool store params
func (o *ExportPoolStoreParams) WithContext(ctx context.Context) *ExportPoolStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export pool store params
func (o *ExportPoolStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export pool store params
func (o *ExportPoolStoreParams) WithHTTPClient(client *http.Client) *ExportPoolStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export pool store params
func (o *ExportPoolStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ExportPoolStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
