// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeletePoolStoreHandlerFunc turns a function with the right signature into a delete pool store handler
type DeletePoolStoreHandlerFunc func(DeletePoolStoreParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePoolStoreHandlerFunc) Handle(params DeletePoolStoreParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeletePoolStoreHandler interface for that can handle valid delete pool store params
type DeletePoolStoreHandler interface {
	Handle(DeletePoolStoreParams, interface{}) middleware.Responder
}

// NewDeletePoolStore creates a new http.Handler for the delete pool store operation
func NewDeletePoolStore(ctx *middleware.Context, handler DeletePoolStoreHandler) *DeletePoolStore {
	return &DeletePoolStore{Context: ctx, Handler: handler}
}

/* DeletePoolStore swagger:route DELETE /admin/poolstore admin deletePoolStore

Delete current state

Delete the contents of the pool store including bookings

*/
type DeletePoolStore struct {
	Context *middleware.Context
	Handler DeletePoolStoreHandler
}

func (o *DeletePoolStore) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePoolStoreParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
