// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/relay/internal/booking/models"
)

// ExportPoolStoreOKCode is the HTTP code returned for type ExportPoolStoreOK
const ExportPoolStoreOKCode int = 200

/*ExportPoolStoreOK export pool store o k

swagger:response exportPoolStoreOK
*/
type ExportPoolStoreOK struct {

	/*
	  In: Body
	*/
	Payload *models.Poolstore `json:"body,omitempty"`
}

// NewExportPoolStoreOK creates ExportPoolStoreOK with default headers values
func NewExportPoolStoreOK() *ExportPoolStoreOK {

	return &ExportPoolStoreOK{}
}

// WithPayload adds the payload to the export pool store o k response
func (o *ExportPoolStoreOK) WithPayload(payload *models.Poolstore) *ExportPoolStoreOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export pool store o k response
func (o *ExportPoolStoreOK) SetPayload(payload *models.Poolstore) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportPoolStoreOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportPoolStoreUnauthorizedCode is the HTTP code returned for type ExportPoolStoreUnauthorized
const ExportPoolStoreUnauthorizedCode int = 401

/*ExportPoolStoreUnauthorized Unauthorized

swagger:response exportPoolStoreUnauthorized
*/
type ExportPoolStoreUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewExportPoolStoreUnauthorized creates ExportPoolStoreUnauthorized with default headers values
func NewExportPoolStoreUnauthorized() *ExportPoolStoreUnauthorized {

	return &ExportPoolStoreUnauthorized{}
}

// WithPayload adds the payload to the export pool store unauthorized response
func (o *ExportPoolStoreUnauthorized) WithPayload(payload interface{}) *ExportPoolStoreUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export pool store unauthorized response
func (o *ExportPoolStoreUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportPoolStoreUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ExportPoolStoreInternalServerErrorCode is the HTTP code returned for type ExportPoolStoreInternalServerError
const ExportPoolStoreInternalServerErrorCode int = 500

/*ExportPoolStoreInternalServerError export pool store internal server error

swagger:response exportPoolStoreInternalServerError
*/
type ExportPoolStoreInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewExportPoolStoreInternalServerError creates ExportPoolStoreInternalServerError with default headers values
func NewExportPoolStoreInternalServerError() *ExportPoolStoreInternalServerError {

	return &ExportPoolStoreInternalServerError{}
}

// WithPayload adds the payload to the export pool store internal server error response
func (o *ExportPoolStoreInternalServerError) WithPayload(payload interface{}) *ExportPoolStoreInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export pool store internal server error response
func (o *ExportPoolStoreInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportPoolStoreInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
