// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Bids Set of booking IDs (bids)
//
// swagger:model Bids
type Bids struct {

	// list bids in string format
	// Required: true
	Bids []string `json:"bids"`
}

// Validate validates this bids
func (m *Bids) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBids(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Bids) validateBids(formats strfmt.Registry) error {

	if err := validate.Required("bids", "body", m.Bids); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this bids based on context it is used
func (m *Bids) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Bids) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Bids) UnmarshalBinary(b []byte) error {
	var res Bids
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
