// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Report report
//
// swagger:model Report
type Report struct {

	// can read
	CanRead bool `json:"can_read,omitempty"`

	// can write
	CanWrite bool `json:"can_write,omitempty"`

	// connected at
	ConnectedAt string `json:"connected_at,omitempty"`

	// expires at
	ExpiresAt string `json:"expires_at,omitempty"`

	// remote addr
	RemoteAddr string `json:"remote_addr,omitempty"`

	// scopes
	Scopes []string `json:"scopes"`

	// topic
	Topic string `json:"topic,omitempty"`

	// user agent
	UserAgent string `json:"user_agent,omitempty"`
}

// Validate validates this report
func (m *Report) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this report based on context it is used
func (m *Report) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Report) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Report) UnmarshalBinary(b []byte) error {
	var res Report
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
