// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SessionHandlerFunc turns a function with the right signature into a session handler
type SessionHandlerFunc func(SessionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SessionHandlerFunc) Handle(params SessionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SessionHandler interface for that can handle valid session params
type SessionHandler interface {
	Handle(SessionParams, interface{}) middleware.Responder
}

// NewSession creates a new http.Handler for the session operation
func NewSession(ctx *middleware.Context, handler SessionHandler) *Session {
	return &Session{Context: ctx, Handler: handler}
}

/*Session swagger:route POST /session/{session_id} session

session

access the specified session

*/
type Session struct {
	Context *middleware.Context
	Handler SessionHandler
}

func (o *Session) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSessionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
