// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/relay/internal/booking/models"
)

// GetCurrentBookingsOKCode is the HTTP code returned for type GetCurrentBookingsOK
const GetCurrentBookingsOKCode int = 200

/*GetCurrentBookingsOK get current bookings o k

swagger:response getCurrentBookingsOK
*/
type GetCurrentBookingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bookings `json:"body,omitempty"`
}

// NewGetCurrentBookingsOK creates GetCurrentBookingsOK with default headers values
func NewGetCurrentBookingsOK() *GetCurrentBookingsOK {

	return &GetCurrentBookingsOK{}
}

// WithPayload adds the payload to the get current bookings o k response
func (o *GetCurrentBookingsOK) WithPayload(payload *models.Bookings) *GetCurrentBookingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current bookings o k response
func (o *GetCurrentBookingsOK) SetPayload(payload *models.Bookings) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentBookingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCurrentBookingsUnauthorizedCode is the HTTP code returned for type GetCurrentBookingsUnauthorized
const GetCurrentBookingsUnauthorizedCode int = 401

/*GetCurrentBookingsUnauthorized Unauthorized

swagger:response getCurrentBookingsUnauthorized
*/
type GetCurrentBookingsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetCurrentBookingsUnauthorized creates GetCurrentBookingsUnauthorized with default headers values
func NewGetCurrentBookingsUnauthorized() *GetCurrentBookingsUnauthorized {

	return &GetCurrentBookingsUnauthorized{}
}

// WithPayload adds the payload to the get current bookings unauthorized response
func (o *GetCurrentBookingsUnauthorized) WithPayload(payload interface{}) *GetCurrentBookingsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current bookings unauthorized response
func (o *GetCurrentBookingsUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentBookingsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCurrentBookingsNotFoundCode is the HTTP code returned for type GetCurrentBookingsNotFound
const GetCurrentBookingsNotFoundCode int = 404

/*GetCurrentBookingsNotFound Not Found

swagger:response getCurrentBookingsNotFound
*/
type GetCurrentBookingsNotFound struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetCurrentBookingsNotFound creates GetCurrentBookingsNotFound with default headers values
func NewGetCurrentBookingsNotFound() *GetCurrentBookingsNotFound {

	return &GetCurrentBookingsNotFound{}
}

// WithPayload adds the payload to the get current bookings not found response
func (o *GetCurrentBookingsNotFound) WithPayload(payload interface{}) *GetCurrentBookingsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current bookings not found response
func (o *GetCurrentBookingsNotFound) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentBookingsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCurrentBookingsInternalServerErrorCode is the HTTP code returned for type GetCurrentBookingsInternalServerError
const GetCurrentBookingsInternalServerErrorCode int = 500

/*GetCurrentBookingsInternalServerError Internal Error

swagger:response getCurrentBookingsInternalServerError
*/
type GetCurrentBookingsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetCurrentBookingsInternalServerError creates GetCurrentBookingsInternalServerError with default headers values
func NewGetCurrentBookingsInternalServerError() *GetCurrentBookingsInternalServerError {

	return &GetCurrentBookingsInternalServerError{}
}

// WithPayload adds the payload to the get current bookings internal server error response
func (o *GetCurrentBookingsInternalServerError) WithPayload(payload interface{}) *GetCurrentBookingsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current bookings internal server error response
func (o *GetCurrentBookingsInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentBookingsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
