// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeletePoolsByGroupIDHandlerFunc turns a function with the right signature into a delete pools by group ID handler
type DeletePoolsByGroupIDHandlerFunc func(DeletePoolsByGroupIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePoolsByGroupIDHandlerFunc) Handle(params DeletePoolsByGroupIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeletePoolsByGroupIDHandler interface for that can handle valid delete pools by group ID params
type DeletePoolsByGroupIDHandler interface {
	Handle(DeletePoolsByGroupIDParams, interface{}) middleware.Responder
}

// NewDeletePoolsByGroupID creates a new http.Handler for the delete pools by group ID operation
func NewDeletePoolsByGroupID(ctx *middleware.Context, handler DeletePoolsByGroupIDHandler) *DeletePoolsByGroupID {
	return &DeletePoolsByGroupID{Context: ctx, Handler: handler}
}

/* DeletePoolsByGroupID swagger:route DELETE /groups/{group_id}/pools groups deletePoolsByGroupId

groups

Delete one or more pool_ids in the group. Return new complete list.

*/
type DeletePoolsByGroupID struct {
	Context *middleware.Context
	Handler DeletePoolsByGroupIDHandler
}

func (o *DeletePoolsByGroupID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePoolsByGroupIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
