// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Idlist idlist
//
// list of ids (in array)
//
// swagger:model idlist
type Idlist []string

// Validate validates this idlist
func (m Idlist) Validate(formats strfmt.Registry) error {
	return nil
}
