// Code generated by go-swagger; DO NOT EDIT.

package pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/timdrysdale/relay/pkg/booking/models"
)

// PoolOKCode is the HTTP code returned for type PoolOK
const PoolOKCode int = 200

/*PoolOK pool o k

swagger:response poolOK
*/
type PoolOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Description `json:"body,omitempty"`
}

// NewPoolOK creates PoolOK with default headers values
func NewPoolOK() *PoolOK {

	return &PoolOK{}
}

// WithPayload adds the payload to the pool o k response
func (o *PoolOK) WithPayload(payload []*models.Description) *PoolOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pool o k response
func (o *PoolOK) SetPayload(payload []*models.Description) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PoolOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Description, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
