// Code generated by go-swagger; DO NOT EDIT.

package pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/timdrysdale/relay/pkg/booking/models"
)

// PostpoolOKCode is the HTTP code returned for type PostpoolOK
const PostpoolOKCode int = 200

/*PostpoolOK postpool o k

swagger:response postpoolOK
*/
type PostpoolOK struct {

	/*
	  In: Body
	*/
	Payload *models.Activity `json:"body,omitempty"`
}

// NewPostpoolOK creates PostpoolOK with default headers values
func NewPostpoolOK() *PostpoolOK {

	return &PostpoolOK{}
}

// WithPayload adds the payload to the postpool o k response
func (o *PostpoolOK) WithPayload(payload *models.Activity) *PostpoolOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the postpool o k response
func (o *PostpoolOK) SetPayload(payload *models.Activity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostpoolOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostpoolUnauthorizedCode is the HTTP code returned for type PostpoolUnauthorized
const PostpoolUnauthorizedCode int = 401

/*PostpoolUnauthorized Unauthorized

swagger:response postpoolUnauthorized
*/
type PostpoolUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostpoolUnauthorized creates PostpoolUnauthorized with default headers values
func NewPostpoolUnauthorized() *PostpoolUnauthorized {

	return &PostpoolUnauthorized{}
}

// WithPayload adds the payload to the postpool unauthorized response
func (o *PostpoolUnauthorized) WithPayload(payload interface{}) *PostpoolUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the postpool unauthorized response
func (o *PostpoolUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostpoolUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostpoolNotFoundCode is the HTTP code returned for type PostpoolNotFound
const PostpoolNotFoundCode int = 404

/*PostpoolNotFound Not Available

swagger:response postpoolNotFound
*/
type PostpoolNotFound struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostpoolNotFound creates PostpoolNotFound with default headers values
func NewPostpoolNotFound() *PostpoolNotFound {

	return &PostpoolNotFound{}
}

// WithPayload adds the payload to the postpool not found response
func (o *PostpoolNotFound) WithPayload(payload interface{}) *PostpoolNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the postpool not found response
func (o *PostpoolNotFound) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostpoolNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
