// Code generated by go-swagger; DO NOT EDIT.

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteActivityByIDParams creates a new DeleteActivityByIDParams object
// with the default values initialized.
func NewDeleteActivityByIDParams() *DeleteActivityByIDParams {
	var ()
	return &DeleteActivityByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteActivityByIDParamsWithTimeout creates a new DeleteActivityByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteActivityByIDParamsWithTimeout(timeout time.Duration) *DeleteActivityByIDParams {
	var ()
	return &DeleteActivityByIDParams{

		timeout: timeout,
	}
}

// NewDeleteActivityByIDParamsWithContext creates a new DeleteActivityByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteActivityByIDParamsWithContext(ctx context.Context) *DeleteActivityByIDParams {
	var ()
	return &DeleteActivityByIDParams{

		Context: ctx,
	}
}

// NewDeleteActivityByIDParamsWithHTTPClient creates a new DeleteActivityByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteActivityByIDParamsWithHTTPClient(client *http.Client) *DeleteActivityByIDParams {
	var ()
	return &DeleteActivityByIDParams{
		HTTPClient: client,
	}
}

/*DeleteActivityByIDParams contains all the parameters to send to the API endpoint
for the delete activity by ID operation typically these are written to a http.Request
*/
type DeleteActivityByIDParams struct {

	/*ActivityID*/
	ActivityID string
	/*PoolID*/
	PoolID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete activity by ID params
func (o *DeleteActivityByIDParams) WithTimeout(timeout time.Duration) *DeleteActivityByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete activity by ID params
func (o *DeleteActivityByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete activity by ID params
func (o *DeleteActivityByIDParams) WithContext(ctx context.Context) *DeleteActivityByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete activity by ID params
func (o *DeleteActivityByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete activity by ID params
func (o *DeleteActivityByIDParams) WithHTTPClient(client *http.Client) *DeleteActivityByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete activity by ID params
func (o *DeleteActivityByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityID adds the activityID to the delete activity by ID params
func (o *DeleteActivityByIDParams) WithActivityID(activityID string) *DeleteActivityByIDParams {
	o.SetActivityID(activityID)
	return o
}

// SetActivityID adds the activityId to the delete activity by ID params
func (o *DeleteActivityByIDParams) SetActivityID(activityID string) {
	o.ActivityID = activityID
}

// WithPoolID adds the poolID to the delete activity by ID params
func (o *DeleteActivityByIDParams) WithPoolID(poolID string) *DeleteActivityByIDParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the delete activity by ID params
func (o *DeleteActivityByIDParams) SetPoolID(poolID string) {
	o.PoolID = poolID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteActivityByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activity_id
	if err := r.SetPathParam("activity_id", o.ActivityID); err != nil {
		return err
	}

	// path param pool_id
	if err := r.SetPathParam("pool_id", o.PoolID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
