// Code generated by go-swagger; DO NOT EDIT.

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/relay/pkg/bc/models"
)

// GetPoolDescriptionByIDReader is a Reader for the GetPoolDescriptionByID structure.
type GetPoolDescriptionByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPoolDescriptionByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPoolDescriptionByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPoolDescriptionByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPoolDescriptionByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPoolDescriptionByIDOK creates a GetPoolDescriptionByIDOK with default headers values
func NewGetPoolDescriptionByIDOK() *GetPoolDescriptionByIDOK {
	return &GetPoolDescriptionByIDOK{}
}

/*GetPoolDescriptionByIDOK handles this case with default header values.

GetPoolDescriptionByIDOK get pool description by Id o k
*/
type GetPoolDescriptionByIDOK struct {
	Payload *models.Description
}

func (o *GetPoolDescriptionByIDOK) Error() string {
	return fmt.Sprintf("[GET /pools/{pool_id}][%d] getPoolDescriptionByIdOK  %+v", 200, o.Payload)
}

func (o *GetPoolDescriptionByIDOK) GetPayload() *models.Description {
	return o.Payload
}

func (o *GetPoolDescriptionByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Description)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPoolDescriptionByIDUnauthorized creates a GetPoolDescriptionByIDUnauthorized with default headers values
func NewGetPoolDescriptionByIDUnauthorized() *GetPoolDescriptionByIDUnauthorized {
	return &GetPoolDescriptionByIDUnauthorized{}
}

/*GetPoolDescriptionByIDUnauthorized handles this case with default header values.

Unauthorized
*/
type GetPoolDescriptionByIDUnauthorized struct {
	Payload interface{}
}

func (o *GetPoolDescriptionByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /pools/{pool_id}][%d] getPoolDescriptionByIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPoolDescriptionByIDUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *GetPoolDescriptionByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPoolDescriptionByIDInternalServerError creates a GetPoolDescriptionByIDInternalServerError with default headers values
func NewGetPoolDescriptionByIDInternalServerError() *GetPoolDescriptionByIDInternalServerError {
	return &GetPoolDescriptionByIDInternalServerError{}
}

/*GetPoolDescriptionByIDInternalServerError handles this case with default header values.

Internal Error
*/
type GetPoolDescriptionByIDInternalServerError struct {
	Payload interface{}
}

func (o *GetPoolDescriptionByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /pools/{pool_id}][%d] getPoolDescriptionByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPoolDescriptionByIDInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *GetPoolDescriptionByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
