// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoreStatus Store status
//
// Counts of groups, pools, activities, booked sessions
//
// swagger:model store_status
type StoreStatus struct {

	// activities
	Activities int64 `json:"activities,omitempty"`

	// bookings
	Bookings int64 `json:"bookings,omitempty"`

	// groups
	Groups int64 `json:"groups,omitempty"`

	// last booking ends
	LastBookingEnds float64 `json:"last_booking_ends,omitempty"`

	// locked
	Locked bool `json:"locked,omitempty"`

	// msg
	Msg string `json:"msg,omitempty"`

	// pools
	Pools int64 `json:"pools,omitempty"`
}

// Validate validates this store status
func (m *StoreStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this store status based on context it is used
func (m *StoreStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoreStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoreStatus) UnmarshalBinary(b []byte) error {
	var res StoreStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
