// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/timdrysdale/relay/pkg/booking/models"
)

// GetStoreStatusOKCode is the HTTP code returned for type GetStoreStatusOK
const GetStoreStatusOKCode int = 200

/*GetStoreStatusOK get store status o k

swagger:response getStoreStatusOK
*/
type GetStoreStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.StoreStatus `json:"body,omitempty"`
}

// NewGetStoreStatusOK creates GetStoreStatusOK with default headers values
func NewGetStoreStatusOK() *GetStoreStatusOK {

	return &GetStoreStatusOK{}
}

// WithPayload adds the payload to the get store status o k response
func (o *GetStoreStatusOK) WithPayload(payload *models.StoreStatus) *GetStoreStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get store status o k response
func (o *GetStoreStatusOK) SetPayload(payload *models.StoreStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStoreStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetStoreStatusUnauthorizedCode is the HTTP code returned for type GetStoreStatusUnauthorized
const GetStoreStatusUnauthorizedCode int = 401

/*GetStoreStatusUnauthorized Unauthorized

swagger:response getStoreStatusUnauthorized
*/
type GetStoreStatusUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetStoreStatusUnauthorized creates GetStoreStatusUnauthorized with default headers values
func NewGetStoreStatusUnauthorized() *GetStoreStatusUnauthorized {

	return &GetStoreStatusUnauthorized{}
}

// WithPayload adds the payload to the get store status unauthorized response
func (o *GetStoreStatusUnauthorized) WithPayload(payload interface{}) *GetStoreStatusUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get store status unauthorized response
func (o *GetStoreStatusUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStoreStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetStoreStatusInternalServerErrorCode is the HTTP code returned for type GetStoreStatusInternalServerError
const GetStoreStatusInternalServerErrorCode int = 500

/*GetStoreStatusInternalServerError get store status internal server error

swagger:response getStoreStatusInternalServerError
*/
type GetStoreStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetStoreStatusInternalServerError creates GetStoreStatusInternalServerError with default headers values
func NewGetStoreStatusInternalServerError() *GetStoreStatusInternalServerError {

	return &GetStoreStatusInternalServerError{}
}

// WithPayload adds the payload to the get store status internal server error response
func (o *GetStoreStatusInternalServerError) WithPayload(payload interface{}) *GetStoreStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get store status internal server error response
func (o *GetStoreStatusInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStoreStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
