// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SetLockHandlerFunc turns a function with the right signature into a set lock handler
type SetLockHandlerFunc func(SetLockParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SetLockHandlerFunc) Handle(params SetLockParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SetLockHandler interface for that can handle valid set lock params
type SetLockHandler interface {
	Handle(SetLockParams, interface{}) middleware.Responder
}

// NewSetLock creates a new http.Handler for the set lock operation
func NewSetLock(ctx *middleware.Context, handler SetLockHandler) *SetLock {
	return &SetLock{Context: ctx, Handler: handler}
}

/* SetLock swagger:route POST /admin/status admin setLock

set/release booking lock

Set whether the bookings are locked or not

*/
type SetLock struct {
	Context *middleware.Context
	Handler SetLockHandler
}

func (o *SetLock) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetLockParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
