// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/relay/pkg/bc/models"
)

// NewAddPoolsByGroupIDParams creates a new AddPoolsByGroupIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddPoolsByGroupIDParams() *AddPoolsByGroupIDParams {
	return &AddPoolsByGroupIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddPoolsByGroupIDParamsWithTimeout creates a new AddPoolsByGroupIDParams object
// with the ability to set a timeout on a request.
func NewAddPoolsByGroupIDParamsWithTimeout(timeout time.Duration) *AddPoolsByGroupIDParams {
	return &AddPoolsByGroupIDParams{
		timeout: timeout,
	}
}

// NewAddPoolsByGroupIDParamsWithContext creates a new AddPoolsByGroupIDParams object
// with the ability to set a context for a request.
func NewAddPoolsByGroupIDParamsWithContext(ctx context.Context) *AddPoolsByGroupIDParams {
	return &AddPoolsByGroupIDParams{
		Context: ctx,
	}
}

// NewAddPoolsByGroupIDParamsWithHTTPClient creates a new AddPoolsByGroupIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddPoolsByGroupIDParamsWithHTTPClient(client *http.Client) *AddPoolsByGroupIDParams {
	return &AddPoolsByGroupIDParams{
		HTTPClient: client,
	}
}

/* AddPoolsByGroupIDParams contains all the parameters to send to the API endpoint
   for the add pools by group ID operation.

   Typically these are written to a http.Request.
*/
type AddPoolsByGroupIDParams struct {

	// GroupID.
	GroupID string

	// Pools.
	Pools models.IDList

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add pools by group ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPoolsByGroupIDParams) WithDefaults() *AddPoolsByGroupIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add pools by group ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPoolsByGroupIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) WithTimeout(timeout time.Duration) *AddPoolsByGroupIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) WithContext(ctx context.Context) *AddPoolsByGroupIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) WithHTTPClient(client *http.Client) *AddPoolsByGroupIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) WithGroupID(groupID string) *AddPoolsByGroupIDParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) SetGroupID(groupID string) {
	o.GroupID = groupID
}

// WithPools adds the pools to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) WithPools(pools models.IDList) *AddPoolsByGroupIDParams {
	o.SetPools(pools)
	return o
}

// SetPools adds the pools to the add pools by group ID params
func (o *AddPoolsByGroupIDParams) SetPools(pools models.IDList) {
	o.Pools = pools
}

// WriteToRequest writes these params to a swagger request
func (o *AddPoolsByGroupIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", o.GroupID); err != nil {
		return err
	}
	if o.Pools != nil {
		if err := r.SetBodyParam(o.Pools); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
