// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/practable/relay/internal/bc/models"
)

// GetGroupDescriptionByIDReader is a Reader for the GetGroupDescriptionByID structure.
type GetGroupDescriptionByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupDescriptionByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupDescriptionByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetGroupDescriptionByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupDescriptionByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGroupDescriptionByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGroupDescriptionByIDOK creates a GetGroupDescriptionByIDOK with default headers values
func NewGetGroupDescriptionByIDOK() *GetGroupDescriptionByIDOK {
	return &GetGroupDescriptionByIDOK{}
}

/* GetGroupDescriptionByIDOK describes a response with status code 200, with default header values.

GetGroupDescriptionByIDOK get group description by Id o k
*/
type GetGroupDescriptionByIDOK struct {
	Payload *models.Description
}

func (o *GetGroupDescriptionByIDOK) Error() string {
	return fmt.Sprintf("[GET /groups/{group_id}][%d] getGroupDescriptionByIdOK  %+v", 200, o.Payload)
}
func (o *GetGroupDescriptionByIDOK) GetPayload() *models.Description {
	return o.Payload
}

func (o *GetGroupDescriptionByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Description)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupDescriptionByIDUnauthorized creates a GetGroupDescriptionByIDUnauthorized with default headers values
func NewGetGroupDescriptionByIDUnauthorized() *GetGroupDescriptionByIDUnauthorized {
	return &GetGroupDescriptionByIDUnauthorized{}
}

/* GetGroupDescriptionByIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetGroupDescriptionByIDUnauthorized struct {
	Payload interface{}
}

func (o *GetGroupDescriptionByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /groups/{group_id}][%d] getGroupDescriptionByIdUnauthorized  %+v", 401, o.Payload)
}
func (o *GetGroupDescriptionByIDUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *GetGroupDescriptionByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupDescriptionByIDNotFound creates a GetGroupDescriptionByIDNotFound with default headers values
func NewGetGroupDescriptionByIDNotFound() *GetGroupDescriptionByIDNotFound {
	return &GetGroupDescriptionByIDNotFound{}
}

/* GetGroupDescriptionByIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetGroupDescriptionByIDNotFound struct {
	Payload interface{}
}

func (o *GetGroupDescriptionByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /groups/{group_id}][%d] getGroupDescriptionByIdNotFound  %+v", 404, o.Payload)
}
func (o *GetGroupDescriptionByIDNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *GetGroupDescriptionByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupDescriptionByIDInternalServerError creates a GetGroupDescriptionByIDInternalServerError with default headers values
func NewGetGroupDescriptionByIDInternalServerError() *GetGroupDescriptionByIDInternalServerError {
	return &GetGroupDescriptionByIDInternalServerError{}
}

/* GetGroupDescriptionByIDInternalServerError describes a response with status code 500, with default header values.

GetGroupDescriptionByIDInternalServerError get group description by Id internal server error
*/
type GetGroupDescriptionByIDInternalServerError struct {
	Payload interface{}
}

func (o *GetGroupDescriptionByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /groups/{group_id}][%d] getGroupDescriptionByIdInternalServerError  %+v", 500, o.Payload)
}
func (o *GetGroupDescriptionByIDInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *GetGroupDescriptionByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
